[colors.primary]
background = "#222222"
foreground = "#F7F1FF"

[colors.cursor]
text = "#222222"
cursor = "#F7F1FF"

[colors.vi_mode_cursor]
text = "#222222"
cursor = "#F7F1FF"

[colors.search.matches]
foreground = "#222222"
background = "#F7F1FF"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#525053"
background = "#F7F1FF"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#131313"
red = "#FC618D"
green = "#7BD88F"
yellow = "#FCE566"
blue = "#5AD4E6"
magenta = "#948AE3"
cyan = "#FD9353"
white = "#FFFFFF"

[colors.bright]
black = "#191919"
red = "#FC618D"
green = "#7BD88F"
yellow = "#FCE566"
blue = "#5AD4E6"
magenta = "#948AE3"
cyan = "#FD9353"
white = "#FFFFFF"

[colors.dim]
black = "#FFFFFF"
red = "#FC618D"
green = "#7BD88F"
yellow = "#FCE566"
blue = "#5AD4E6"
magenta = "#948AE3"
cyan = "#FD9353"
white = "#525053"
